// id INT AUTO_INCREMENT PRIMARY KEY,
// name VARCHAR(100),
// category_id VARCHAR(50),
// type_id VARCHAR(100),
// price CHAR(10),
// stock INT(255),
// manufacturer VARCHAR(100),
// expiry_date VARCHAR(100),
// batch_number VARCHAR(100),
// description VARCHAR(100)