const crypto = require('crypto');


class Payment{
    static #merchantId = process.env.MERCHANT_ID
    static #merchantSecret = process.env.MERCHANT_SECRET;
    static #url=process.env.PAYMENT_GATEWAY_SANDBOX;

    constructor(){

    }


    static #createHash({orderId , amount ,currency = "LKR" }){

        const amountFormatted  = parseFloat( amount ).toLocaleString( 'en-us', { minimumFractionDigits : 2 } ).replaceAll(',', '');
        const hashedSecret = crypto.createHash('md5').update(this.#merchantSecret , 'utf-8').digest('hex').toUpperCase();
        const hash = crypto.createHash('md5').update(merchantId + orderId + amountFormatted + currency + hashedSecret)

        return hash;
    }


    // merchant_id - PayHere Merchant ID
    // return_url - URL to redirect users when payment is approved
    // cancel_url - URL to redirect users when user cancel the payment
    // notify_url - URL to callback the status of the payment (Needs to be a URL accessible on a public IP/domain)
    // first_name - Customer’s First Name
    // last_name - Customer’s Last Name
    // email - Customer’s Email
    // phone - Customer’s Phone No
    // address - Customer’s Address Line1 + Line2
    // city - Customer’s City
    // country - Customer’s Country
    // order_id - Order ID generated by the merchant
    // items - Item title or Order/Invoice number
    // currency - Currency Code (LKR/USD)
    // amount - Total Payment Amount
    // hash - Generated hash value as mentioned below (*Required from 2023-01-16)  
    static create({
        firstName : first_name  , 
        lastName : last_name,
        email , 
        phone , 
        address,
        city,
        country,
        order_id,
        items,
        currency,
        amount,
    }){
        const checkoutObj = {
            first_name , 
            last_name , 
            email , 
            phone , 
            address , 
            city , 
            country , 
            order_id , 
            items , 
            currency , 
            amount , 
            hash : this.#createHash(),
        }


        console.log(checkoutObj);
    }

    
}

module.exports = Payment;